### ISSUE TITLE
Erreur elif Paul Morgan

### ISSUE THREAD

**Issue by PaulGillon** [Aherbeth/IUT-bash#1]
#!/bin/bash

nbAleatoire= ${RANDOM:0:2}
state= "false"
while [ $state -eq "false" ]
do
    echo "Entrer un nombre entre 0 et 99"
    read nbUser

if [ $nbUser -eq $nbAleatoire ]; then
        echo "Bravo"
        state= "true"

elif [ $nbUser -gt $nbAleatoire ]
        echo "Inferieur"
        
elif [ $nbUser -lt $nbAleatoire ]
echo "Superieur"
fi
done

**Comment by Aherbeth** [comment]
on a plusieurs soucis : 
on retire les espaces dans les affectations de variables pour être tranquilles. 
ensuite le `-eq` ne fonctionne pas avec du texte masi avec des "nombres", on le remplacera donc avec `==`.
Les `elif` nécessitent un `then`.
Et on oublie pas les double quotes autour des variables qu'on appelle.
Une fois corrigé et indenté ça nous donne ça : 
```bash
#!/bin/bash
nbAleatoire=${RANDOM:0:2}
state="false"
echo "alea : $nbAleatoire"
while [ $state == "false" ]
do
    echo "Entrer un nombre entre 0 et 99"
    read -r nbUser

    if [ "${nbUser}" -eq $nbAleatoire ]; then
        echo "Bravo"
        state="true"

    elif [ "${nbUser}" -gt $nbAleatoire ]
    then
        echo "Inferieur"

    elif [ "${nbUser}" -lt $nbAleatoire ]
    then
        echo "Superieur"
    fi
done
```
