### ISSUE TITLE
Comparateur "différant de" ne fonctionne pas sur les strings

### ISSUE THREAD

**Issue by cassagnebertrand** [Aherbeth/IUT-bash#2]
```bash
inputChoix="u"
while [ $inputChoix != "n" ] || [ $inputChoix != "N" ] || [ $inputChoix != "o" ] || [ $inputChoix != "O" ]; do
  echo "Veux tu enregistrer ton score ? o/n"
  read inputChoix
  if [ $inputChoix == "n" ] || [ $inputChoix == "N" ]; then
      echo "Trés bien CIAO"
  elif [ $inputChoix == "o" ] || [ $inputChoix == "O" ]; then
      echo "test"
  else
      echo ""
  fi
done
```

**Comment by Aherbeth** [comment]
En fait le comparateur fonctionne bien, c'est juste qu'il y a un petit couac de logique sur les `||` et les `&&`
la succession des `||` peut être interprété de la sorte : 
Si l'un des choix est vrai on lance l'exécution. 
Donc même si `inputChoix`vaut `n` par exemple, les 3 autre test seront quand-même validés. et comme on cherche la véracité sur un seul des 4 tests (ce que symbolise le `||`), on passe forcément à travers.
Pour régler le soucis, il suffit de remplacer les `||` par des `&&`.
Ce qui implique que si une seule des condition n'est pas remplie, on arrête la boucle. 

```bash 
#!/bin/bash
inputChoix="u"
while [ $inputChoix != "n" ] && [ $inputChoix != "N" ] && [ $inputChoix != "o" ] && [ $inputChoix != "O" ]; do
    echo "Veux tu enregistrer ton score ? o/n"
    read -r inputChoix
    if [ "$inputChoix" == "n" ] || [ "$inputChoix" == "N" ]; then
        echo "Trés bien CIAO"
    elif [ "$inputChoix" == "o" ] || [ "$inputChoix" == "O" ]; then
        echo "test"
    else
        echo ""
    fi
done
```
ça fonctionnera beaucoup mieux :)

**Comment by cassagnebertrand** [comment]
Parfait, j'avais trouvé une autre solution, mais beaucoup moins propre merci !
```bash
choixValidation=false
while [ $choixValidation = false ]; do
  echo "Veux tu enregistrer ton score ? o/n"
  read inputChoix
    if [ $inputChoix == "n" ] || [ $inputChoix == "N" ]; then
      choixValidation=true
      echo "Trés bien CIAO"
    elif [ $inputChoix == "o" ] || [ $inputChoix == "O" ]; then
      choixValidation=true
      echo "Parfait !"
    fi
done
```

**Comment by Aherbeth** [comment]
D'expérience, les booléens peuvent parfois être capricieux (ou en tous cas ne pas reprśenter ce qu'on pense d'un booléen) en bash. la ruse est souvent de les traiter par `0` et `1`.

N'hésites pas à utiliser les blocs de code genre
 \`\`\`bash
 mes commandes qui vont garder l'indentation et la coloration syntaxique ;)
  \`\`\`
